export const CustomerService = [
  {
    id: 1,
    nombre: "Raul Alvarez",
    ciudad: "Manta",
    estado: "Activo",
    actividades: "12",
  },
  {
    id: 2,
    nombre: "Raul Alvarez",
    ciudad: "Portoviejo",
    estado: "Activo",
    actividades: "15",
  },
  {
    id: 3,
    nombre: "Raul Alvarez",
    ciudad: "Manta",
    estado: "Inactivo",
    actividades: "13",
  },
  {
    id: 4,
    nombre: "Raul Alvarez",
    ciudad: "Manta",
    estado: "Activo",
    actividades: "17",
  },
  {
    id: 5,
    nombre: "Raul Alvarez",
    ciudad: "Manta",
    estado: "Activo",
    actividades: "12",
  },
  {
    id: 6,
    nombre: "Raul Alvarez",
    ciudad: "Manta",
    estado: "Inactivo",
    actividades: "12",
  },
  {
    id: 7,
    nombre: "Raul Alvarez",
    ciudad: "Manta",
    estado: "Inactivo",
    actividades: "12",
  },
  {
    id: 8,
    nombre: "Raul Alvarez",
    ciudad: "Manta",
    estado: "Activo",
    actividades: "19",
  },
  {
    id: 9,
    nombre: "Raul Alvarez",
    ciudad: "Manta",
    estado: "Activo",
    actividades: "20",
  },
  {
    id: 10,
    nombre: "Raul Alvarez",
    ciudad: "Manta",
    estado: "Activo",
    actividades: "12",
  },
];
